### ISSUE TITLE
downloader.download 의 last_date 인자의 type은 str 이지만, 디폴트 값은 int 값임.

### ISSUE THREAD

**Issue by daewonyoon** [jason9693/NNST-Naver-News-for-Standard-and-Technology-Database#1]
last_date 인자를 생략하였을 때, 에러가 발생함.

```
C:\Users\user>py -3.6
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from nnst.downloader import download
>>> download(10, 'nnst_test.csv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python3664\lib\site-packages\nnst\downloader.py", line 22, in download
    date = __date_decrease__(date)
  File "D:\Python3664\lib\site-packages\nnst\downloader.py", line 51, in __date_decrease__
    t = time.strptime(news_date, '%Y%m%d')
  File "D:\Python3664\lib\_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "D:\Python3664\lib\_strptime.py", line 329, in _strptime
    raise TypeError(msg.format(index, type(arg)))
TypeError: strptime() argument 0 must be str, not <class 'int'>
```

실은 last_date 인자가 어떤 type 인지 확인하려 소스를 찾아봤을 때, 
디폴트 값을 보고 정수형이라고 생각해서 살짝 헷갈렸음.

**Comment by jason9693** [comment]
@daewonyoon  https://github.com/jason9693/NNST-Naver-News-for-Standard-and-Technology-Database/commit/681d6c63e1230718a2472556f5dbebe563a2fe8d

수정했습니다. 이슈 감사합니다!! 조만간 pypi에도 업로드 시키겠습니다!!!
